[theme]
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"

[server]
headless = true
port = 8502
enableXsrfProtection = true
enableCORS = false
maxUploadSize = 50

[browser]
gatherUsageStats = false

[client]
showErrorDetails = false
toolbarMode = "minimal"